-- Noctalia palette via base16-nvim. lua/matugen.lua is generated by the
-- Noctalia neovim template (git-ignored). Revert: point default.lua back
-- to another theme, e.g. `ln -sf catppuccin.lua default.lua`.
local function apply()
    package.loaded["matugen"] = nil
    local ok, matugen = pcall(require, "matugen")
    if not ok then
        return
    end
    matugen.setup()
    -- keep the alacritty/tmux transparency blend
    for _, group in ipairs({ "Normal", "NormalNC", "SignColumn", "EndOfBuffer" }) do
        vim.api.nvim_set_hl(0, group, { bg = "NONE" })
    end
end

apply()

-- Noctalia's post_hook sends SIGUSR1 to every nvim on theme change
vim.api.nvim_create_autocmd("Signal", {
    pattern = "SIGUSR1",
    group = vim.api.nvim_create_augroup("noctalia_theme", { clear = true }),
    callback = function()
        -- only re-apply while base16 is the active theme (noctalia-nvim-theme may
        -- have switched default.lua to a native colorscheme for this palette)
        local default = vim.fn.stdpath("config") .. "/lua/colorschemes-config/default.lua"
        if vim.fn.resolve(default):match("noctalia%.lua$") then
            vim.schedule(apply)
        end
    end,
})
